[build]
publish = "public"
command = "git submodule update --init --recursive && hugo --forceSyncStatic"

[context.production.environment]
HUGO_VERSION = "0.155.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "git submodule update --init --recursive && hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.155.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.155.2"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.155.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"
